language: node_js
node_js:
    - "0.10"
script: node_modules/karma/bin/karma start my.conf.js --single-run --browsers PhantomJS
sudo: false
cache:
  directories:
    - node_modules
before_install:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
before_script:
    - npm install
deploy:
    - provider: codedeploy
      access_key_id: $AWS_KEY
      secret_access_key: $AWS_SECRET
      application: PokeCard
      deployment_group: testing
      region: us-east-1
before_deploy:
    - rvm 1.9.3 do gem install aws-sdk -v 2.1.36