language: node_js
node_js:
    - "0.10"
script: node_modules/karma/bin/karma start my.conf.js --single-run --browsers PhantomJS
before_install:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
before_script:
    - npm install

deploy:
    - provider: codedeploy
      access_key_id: *1
      secret_access_key: *2
      application: PokeCard
      deployment_group: testing
      on:
        all_branches: true
      region: us-east-1a