<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Auth;

class Message extends Model
{
    protected $primaryKey = 'id_message';
	protected $fillable = [
		'text',
		'id_user',
		'id_user_from',
		'id_status_message'
	];
	
	public static function create(array $attributes = [])
	{
		if(isset($attributes['id_user_from']) === false)
			$attributes['id_user_from'] = (Auth::check())?Auth::user()->id_user:1;
		
		return parent::create($attributes); // TODO: Change the autogenerated stub
	}
	
	
	public function status()
	{
		return $this->hasOne(StatusMessage::class,'id_status_message','id_status_message');
	}
	
	public function from()
	{
		return $this->hasOne(User::class,'id_user','id_user_from')->select(['login','id_user']);
	}
	
}
