<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Facades\Auth;

class Want extends Model
{
    use SoftDeletes;

    protected $primaryKey = 'id_want';
    protected $fillable = [
        'id_user',
        'id_card',
        'pp',
        'id_status_want',
        'foil',
        'reverse_foil'
    ];

    public function status()
    {
        return $this->hasOne(StatusWant::class,'id_status_want','id_status_want');
    }

    public function card()
    {
        return $this->hasOne(Cards::class,'id_card','id_card');
    }

    public function user()
    {
        return $this->hasOne(User::class,'id_user','id_user');
    }

    public static function create(array $attributes = [])
    {
        if(isset($attributes['id_user']) == false || $attributes['id_user'] == '')
            $attributes['id_user'] = Auth::user()->id_user;

        return parent::create($attributes); // TODO: Change the autogenerated stub
    }


}
